# -*- coding: utf-8 -*-
"""Confidence-Checked Action Planner.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18MGMJ6qefypD_NJ7i-UKTzw1QrE1pSsO
"""

!pip install transformers accelerate torch pillow gtts

from transformers import Qwen2VLForConditionalGeneration, AutoProcessor
import torch
processor = AutoProcessor.from_pretrained("Qwen/Qwen2-VL-2B-Instruct")
model = Qwen2VLForConditionalGeneration.from_pretrained(
    "Qwen/Qwen2-VL-2B-Instruct",
    torch_dtype=torch.float16,
    low_cpu_mem_usage=True
).to("cuda")

def ask_text_only(prompt):
    messages = [{"role": "user", "content": [{"type": "text", "text": prompt}]}]
    text_prompt = processor.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)
    inputs = processor(text=[text_prompt], return_tensors="pt").to("cuda")
    output = model.generate(**inputs, max_new_tokens=30)
    result = processor.batch_decode(output, skip_special_tokens=True)[0]
    return result.split("assistant\n")[-1].strip()

grid_size = 5
objects = {
    "cup": (1, 3),
    "book": (4, 0),
    "ball": (2, 2)
}

def get_robot_action(instruction):
    object_list = ", ".join(objects.keys())
    base_prompt = f"You are controlling a robot in a room with these objects: {object_list}. The instruction is: '{instruction}'. Which single object should the robot move to? Answer with just the object name, or say 'unclear' if ambiguous."

    response1 = ask_text_only(base_prompt)
    response2 = ask_text_only(base_prompt + " Be very specific and answer with exactly one word.")

    r1 = response1.strip().lower()
    r2 = response2.strip().lower()

    if r1 != r2 or r1 not in objects:
        return f"AMBIGUOUS INSTRUCTION: Could you clarify what you mean by '{instruction}'?", None
    else:
        return f"Moving to: {r1}", r1

import matplotlib.pyplot as plt

def move_robot_to(target_object):
    target_pos = objects[target_object]
    plt.figure(figsize=(4,4))
    for obj, pos in objects.items():
        color = 'green' if obj == target_object else 'blue'
        size = 400 if obj == target_object else 200
        plt.scatter(pos[0], pos[1], c=color, s=size)
        plt.text(pos[0], pos[1]+0.2, obj)
    plt.xlim(-1, grid_size); plt.ylim(-1, grid_size)
    plt.title(f"Robot target: {target_object}")
    plt.show()

test_instructions = ["move to the cup", "go to it", "pick up the round thing", "move there"]

for instruction in test_instructions:
    message, target = get_robot_action(instruction)
    print(f"Instruction: '{instruction}' -> {message}")
    if target:
        move_robot_to(target)



objects = {
    "cup": (1, 3),
    "book": (4, 0),
    "ball": (2, 2),
    "phone": (0, 4),
    "bottle": (3, 4)
}

test_instructions = [
    "move to the cup",
    "bring me the thing I read",
    "get the thing I drink from",
    "hand me the thing that rings",
    "grab the round one",
    "go to it",
]

for instruction in test_instructions:
    message, target = get_robot_action(instruction)
    print(f"Instruction: '{instruction}' -> {message}")
    if target:
        move_robot_to(target)

import matplotlib.pyplot as plt

object_colors = {
    "cup": "red",
    "book": "orange",
    "ball": "purple",
    "phone": "brown",
    "bottle": "teal"
}

def move_robot_to(target_object, filename=None):
    plt.figure(figsize=(4,4))
    for obj, pos in objects.items():
        color = object_colors.get(obj, "gray")
        if obj == target_object:
            plt.scatter(pos[0], pos[1], c=color, s=500, marker='*', edgecolors='black', linewidths=2)
        else:
            plt.scatter(pos[0], pos[1], c=color, s=200)
        plt.text(pos[0], pos[1]+0.25, obj)
    plt.xlim(-1, grid_size); plt.ylim(-1, grid_size)
    plt.title(f"Robot target: {target_object}")
    if filename:
        plt.savefig(filename, bbox_inches='tight')
    plt.show()

import pandas as pd
from google.colab import files

results = []
for i, instruction in enumerate(test_instructions):
    message, target = get_robot_action(instruction)
    print(f"Instruction: '{instruction}' -> {message}")
    image_file = None
    if target:
        image_file = f"robot_result_{i}.png"
        move_robot_to(target, filename=image_file)
    results.append({"instruction": instruction, "result": message, "image": image_file})

df = pd.DataFrame(results)
df.to_csv("robot_results.csv", index=False)

# Now download everything
files.download("robot_results.csv")
for r in results:
    if r["image"]:
        files.download(r["image"])

from google.colab import files
import os

for i in range(len(test_instructions)):
    filename = f"robot_result_{i}.png"
    if os.path.exists(filename):
        files.download(filename)

